### ISSUE TITLE
من فضلك تحديد مصدر قاعدة البيانات 

### ISSUE THREAD

**Issue by badre429** [mahmoudBens/Nomenclature-des-medicaments-en-algerie#1]

**Comment by mahmoudBens** [comment]
هي كانت في ملف إيكسل خاص بالوزارة 
وحولناها ل sql

**Comment by inteclix** [comment]
http://www.sante.gov.dz/images/pharmacie/nomenclature-au-31-Dcembre-2019.xlsx

**Comment by bilalchawi** [comment]
l'excel ta3 lwazar fih des fautes kima dwa ta3 irys dosage fl'excel 6mg . wflvignette 4mg . so b careful
![01](https://user-images.githubusercontent.com/68698612/89281202-0818fa00-d64a-11ea-9e34-b86039217f4a.PNG)

**Comment by kzelda** [comment]
![image](https://user-images.githubusercontent.com/592467/89730575-1e56f980-da40-11ea-9f19-4499e6b85594.png)
